- name: install and start nginx
  host: ansible
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.packages:
      name: nginx
      state: present

  - name: start nginx
    service:
      name: nginx
      state: started
      enable: yes
