- name: about variables
  hosts: ansible
  vars:
    game: cricket
    player: vinod
    type: right hand batsman

  tasks:
  - debug:
      msg: "hii, i am playing {{ game }}, my name is {{ player }}, i am {{ type }}"