- name: overriding variabels
  hosts: localhost
  connection: local
  vars:
    game: cricket
    player: vinod
    type: right hand batsman

  tasks:
  - name: print the information
    vars:
    game: cricket2
    debug:
      msg: "hii, i am playing {{ game }}, my name is {{ player }}, i am {{ type }}"