- name: calling from another yaml file
  hosts: localhost
  connection: local
  vars_files:
  - common.yaml
  tasks:
  - debug:
      msg: " hii, i am playing {{ game }}, my name is {{ player }}, i am {{ type }}"