[ansible]
172.31.24.129 ;GAME="ansible for node-1 server"  # these are called as  individual vars
;172.31.29.156 ;GAME="ansible for node-2 server"    # & it's override the group vars


[local]
localhost



[local:vars]
GAME=hand ball
POSITION=goal keeper

; [ansible:vars]
; GAME=hand ball
; POSITION=goal keeper